/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Mon Nov 03 15:14:57 2025 */

/* parameterized module instance */
PLL __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
