`timescale 1ns / 1ps

///////////////////////////////////////////////////////////////////////////////////////////////////
// File: sim/ufm_config_tb.v
//
// Exercises src/ufm_config.v against the behavioural EFB in sim/ufm_efb_model.v.
// The loader writes into registers.v through a byte port, so the bench scores the
// stream of (address, data) writes it emits.
//
//   case 0  a good calibration record   -> valid, exactly the expected 18 writes
//   case 1  blank (erased) UFM          -> no writes at all, defaults survive
//   case 2  good magic, wrong checksum  -> no writes at all
//   case 3  EFB that never acknowledges -> watchdog trips, cfg_done still rises
//   case 4  the record built by tools/make_ufm_record.py, read from
//           sim/calibration_example.mem -> must behave exactly like case 0.
//           This is the cross-check that the generator and the RTL agree on the
//           layout, the byte order and the checksum.
//
// Run:  iverilog -g2005 -o ufm_tb.out -s ufm_config_tb \
//                 sim/ufm_config_tb.v sim/ufm_efb_model.v src/ufm_config.v && vvp ufm_tb.out
///////////////////////////////////////////////////////////////////////////////////////////////////

module ufm_config_tb;

reg wb_clk  = 1'b0;                 // EFB WISHBONE domain
reg reg_clk = 1'b0;                 // register file domain
reg rstn    = 1'b0;

always #10 wb_clk  = ~wb_clk;       // 50 MHz
always #20 reg_clk = ~reg_clk;      // 25 MHz

integer errors = 0;

// The register values the good record should produce, must agree with
// sim/ufm_efb_model.v.
localparam [31:0] EXP_PW_LOW  = 32'h00000123;   // registers 0x00..0x03
localparam [31:0] EXP_PW_HIGH = 32'h000003C0;   // registers 0x04..0x07
localparam [31:0] EXP_RATE    = 32'h000112A9;   // registers 0x08..0x0B
localparam [15:0] EXP_DRIVE   = 16'h0B40;       // registers 0x10..0x11
localparam [15:0] EXP_PWM     = 16'h0400;       // registers 0x12..0x13
localparam [15:0] EXP_CW      = 16'h0380;       // registers 0x14..0x15

//--------------------------------------------------------------------------------------------------
// Four independent loaders, one per case
//--------------------------------------------------------------------------------------------------
wire [4:0] done, valid, we;
wire [7:0] addr    [0:4];
wire [7:0] data    [0:4];
wire [7:0] status  [0:4];
wire [7:0] version [0:4];

// Case 3: hold the model in reset so it never acknowledges.  The loader has to
// fall out on its watchdog instead of hanging with cfg_done low.
// Held high out of reset like top.v's efb_wb_rst; case 3 is never released
// so its EFB never acknowledges and the loader must fall out on its watchdog.
reg [4:0] efb_rst = 5'b11111;

genvar g;
generate
for (g = 0; g < 5; g = g + 1) begin : dut
    wire       ecyc, estb, ewe, eack;
    wire [7:0] eadr, edw, edr;

    ufm_config #(
        .UFM_PAGE   (0),
        .BOOT_DELAY (16),        // shortened for simulation
        .EN_DELAY   (8),
        .TIMEOUT    (20000)
    ) u (
        .wb_clk     (wb_clk),
        .reg_clk    (reg_clk),
        .rstn       (rstn),
        .wb_cyc_o   (ecyc),
        .wb_stb_o   (estb),
        .wb_we_o    (ewe),
        .wb_adr_o   (eadr),
        .wb_dat_o   (edw),
        .wb_dat_i   (edr),
        .wb_ack_i   (eack),
        .cfg_we     (we[g]),
        .cfg_addr   (addr[g]),
        .cfg_data   (data[g]),
        .cfg_done   (done[g]),
        .cfg_valid  (valid[g]),
        .cfg_version(version[g]),
        .cfg_status (status[g])
    );

    efb_i2c_model efb (
        .wb_clk_i   (wb_clk),
        .wb_rst_i   (efb_rst[g]),
        .wb_cyc_i   (ecyc),
        .wb_stb_i   (estb),
        .wb_we_i    (ewe),
        .wb_adr_i   (eadr),
        .wb_dat_i   (edw),
        .wb_dat_o   (edr),
        .wb_ack_o   (eack),
        .wbc_ufm_irq()
    );
end
endgenerate

defparam dut[0].efb.CASE_ID = 0;   // good record
defparam dut[1].efb.CASE_ID = 1;   // blank UFM
defparam dut[2].efb.CASE_ID = 2;   // bad checksum
defparam dut[3].efb.CASE_ID = 3;   // good record, but the EFB is wedged
defparam dut[4].efb.CASE_ID = 4;   // record generated by the Python tool
defparam dut[4].efb.MEM_FILE = "sim/calibration_example.mem";


//--------------------------------------------------------------------------------------------------
// Score the write stream: a shadow register file plus a per-address write count.
//--------------------------------------------------------------------------------------------------
reg [7:0] shadow  [0:4][0:255];
integer   wcount  [0:4][0:255];
integer   wtotal  [0:4];

integer c, a;

generate
for (g = 0; g < 5; g = g + 1) begin : mon
    always @(posedge reg_clk) if (we[g]) begin
        shadow[g][addr[g]] = data[g];
        wcount[g][addr[g]] = wcount[g][addr[g]] + 1;
        wtotal[g]          = wtotal[g] + 1;
        // A write to 0x20..0x23 would mean the record could reach static_control
        // or dynamic_control.  The address mapping must make that impossible.
        if (addr[g] >= 8'h20) begin
            $display("FAIL case%0d: loader wrote control register %02h", g, addr[g]);
            errors = errors + 1;
        end
    end
end
endgenerate

//--------------------------------------------------------------------------------------------------
task chk; input [255:0] name; input [31:0] got; input [31:0] exp; begin
    if (got !== exp) begin
        $display("FAIL %0s: got %0h expected %0h", name, got, exp);
        errors = errors + 1;
    end
end endtask

function bypass_seen; input integer ci; begin
    case (ci)
    0: bypass_seen = dut[0].efb.saw_bypass;
    1: bypass_seen = dut[1].efb.saw_bypass;
    2: bypass_seen = dut[2].efb.saw_bypass;
    3: bypass_seen = dut[3].efb.saw_bypass;
    default: bypass_seen = dut[4].efb.saw_bypass;
    endcase
end endfunction

// Read a little endian value back out of the shadow register file.
function [31:0] rd32; input integer ci; input integer base; begin
    rd32 = {shadow[ci][base+3], shadow[ci][base+2], shadow[ci][base+1], shadow[ci][base+0]};
end endfunction

function [31:0] rd16; input integer ci; input integer base; begin
    rd16 = {16'h0, shadow[ci][base+1], shadow[ci][base+0]};
end endfunction

initial begin
    for (c = 0; c < 5; c = c + 1) begin
        wtotal[c] = 0;
        for (a = 0; a < 256; a = a + 1) begin
            shadow[c][a] = 8'hXX;
            wcount[c][a] = 0;
        end
    end

    rstn    = 1'b0;
    efb_rst = 5'b11111;
    repeat (5) @(posedge reg_clk);
    rstn    = 1'b1;
    efb_rst = 5'b01000;          // release every EFB except case 3's

    wait (done[0] && done[1] && done[2] && done[4]);
    repeat (25000) @(posedge reg_clk);          // let the watchdog case finish too

    $display("--------------------------------------------------------");
    $display("case 0 good record : done=%b valid=%b status=%02h version=%02h writes=%0d",
             done[0], valid[0], status[0], version[0], wtotal[0]);
    chk("case0 done",      {31'h0, done[0]},  32'h1);
    chk("case0 valid",     {31'h0, valid[0]}, 32'h1);
    chk("case0 committed", {31'h0, status[0][5]}, 32'h1);
    chk("case0 version",   {24'h0, version[0]},   32'h1);
    chk("case0 write count", wtotal[0], 32'd18);   // 12 limit bytes + 6 current bytes
    chk("case0 reg 0x00 pulse_width_lower_limit", rd32(0, 8'h00), EXP_PW_LOW);
    chk("case0 reg 0x04 pulse_width_upper_limit", rd32(0, 8'h04), EXP_PW_HIGH);
    chk("case0 reg 0x08 rate_lower_limit",        rd32(0, 8'h08), EXP_RATE);
    chk("case0 reg 0x10 drive_current_limit",     rd16(0, 8'h10), {16'h0, EXP_DRIVE});
    chk("case0 reg 0x12 pwm_current_limit",       rd16(0, 8'h12), {16'h0, EXP_PWM});
    chk("case0 reg 0x14 cw_current_limit",        rd16(0, 8'h14), {16'h0, EXP_CW});
    // Every restored byte must be written exactly once.
    for (a = 0; a < 256; a = a + 1)
        if (wcount[0][a] > 1) begin
            $display("FAIL case0: register %02h written %0d times", a, wcount[0][a]);
            errors = errors + 1;
        end

    $display("case 1 blank UFM   : done=%b valid=%b status=%02h writes=%0d",
             done[1], valid[1], status[1], wtotal[1]);
    chk("case1 done",     {31'h0, done[1]},      32'h1);
    chk("case1 valid",    {31'h0, valid[1]},     32'h0);
    chk("case1 magic_ok", {31'h0, status[1][2]}, 32'h0);
    chk("case1 write count", wtotal[1], 32'd0);

    $display("case 2 bad csum    : done=%b valid=%b status=%02h writes=%0d",
             done[2], valid[2], status[2], wtotal[2]);
    chk("case2 done",     {31'h0, done[2]},      32'h1);
    chk("case2 valid",    {31'h0, valid[2]},     32'h0);
    chk("case2 magic_ok", {31'h0, status[2][2]}, 32'h1);
    chk("case2 csum_ok",  {31'h0, status[2][3]}, 32'h0);
    chk("case2 write count", wtotal[2], 32'd0);

    $display("case 3 wedged EFB  : done=%b valid=%b status=%02h writes=%0d",
             done[3], valid[3], status[3], wtotal[3]);
    chk("case3 done",    {31'h0, done[3]},      32'h1);
    chk("case3 valid",   {31'h0, valid[3]},     32'h0);
    chk("case3 timeout", {31'h0, status[3][4]}, 32'h1);
    chk("case3 write count", wtotal[3], 32'd0);

    $display("case 4 tool record : done=%b valid=%b status=%02h version=%02h writes=%0d",
             done[4], valid[4], status[4], version[4], wtotal[4]);
    chk("case4 done",      {31'h0, done[4]},    32'h1);
    chk("case4 valid",     {31'h0, valid[4]},   32'h1);
    chk("case4 version",   {24'h0, version[4]}, 32'h1);
    chk("case4 write count", wtotal[4], 32'd18);
    chk("case4 reg 0x00 pulse_width_lower_limit", rd32(4, 8'h00), EXP_PW_LOW);
    chk("case4 reg 0x04 pulse_width_upper_limit", rd32(4, 8'h04), EXP_PW_HIGH);
    chk("case4 reg 0x08 rate_lower_limit",        rd32(4, 8'h08), EXP_RATE);
    chk("case4 reg 0x10 drive_current_limit",     rd16(4, 8'h10), {16'h0, EXP_DRIVE});
    chk("case4 reg 0x12 pwm_current_limit",       rd16(4, 8'h12), {16'h0, EXP_PWM});
    chk("case4 reg 0x14 cw_current_limit",        rd16(4, 8'h14), {16'h0, EXP_CW});

    // The hardened I2C and SPI ports are only restored after ISC_DISABLE is
    // followed by BYPASS, so every run that reached the EFB must have sent it.
    for (c = 0; c < 5; c = c + 1) begin
        if (c == 3) begin
            // wedged EFB, nothing was ever accepted
        end else if (!bypass_seen(c)) begin
            $display("FAIL case%0d: BYPASS (0xFF) was never sent", c);
            errors = errors + 1;
        end
    end

    $display("--------------------------------------------------------");
    if (errors == 0) $display("ufm_config_tb: PASS");
    else             $display("ufm_config_tb: %0d FAILURE(S)", errors);
    $finish;
end

initial begin
    #50_000_000;
    $display("ufm_config_tb: TIMEOUT, the bench itself never finished");
    $finish;
end

endmodule
